run:
  timeout: 10m
  issues-exit-code: 1
  tests: false  # Do not lint test files
  modules-download-mode: readonly
  allow-parallel-runners: true
  skip-dirs:
    - internal/testutil
  skip-files:
    - ".*_test\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: false
    fieldalignment: false
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/datacrunch-io/datacrunch-sdk-go

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - dogsled
    - dupword
    - embeddedstructfieldcheck
    - errcheck
    - exhaustive
    - exptostd
    - fatcontext
    - funcorder
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gofmt
    - goimports
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - iface
    - importas
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilnesserr
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - rowserrcheck
    - staticcheck
    - tagalign
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
    goconst:
      min-len: 5
    nolintlint:
      require-specific: true
    perfsprint:
      strconcat: false
    predeclared:
      ignore:
        - new
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - funlen
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  exclude-files:
    - ".*_test\\.go$"
    - "internal/testutil/"
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

severity:
  default-severity: error
  case-sensitive: false